local sound = {
    "grotto/common/archive_lockbox/open",
            "grotto/common/archive_lockbox/hit",
            "grotto/common/archive_lockbox/LP",
            "grotto/common/archive_lockbox/taunt",
            "grotto/common/archive_lockbox/use",
            "dontstarve/common/together/packaged",
            "dontstarve/common/together/sculptures/shake",
            "dontstarve/wilson/rock_break",
            "dontstarve/HUD/collect_resource",
            "dontstarve/wilson/equip_item",
            "dontstarve/common/dropGeneric",
            "dontstarve/common/fireOut",
            "dangerous_sea/creatures/shark/swim_LP",
            "wanda2/characters/wanda/watch/MarkPosition",
            "dontstarve/common/telebase_gemplace",
            "moonstorm/characters/wagstaff/talk_single",  --------------------
            "moonstorm/common/alterguardian_contained/static_LP",
            "moonstorm/common/alterguardian_contained/close",
            "moonstorm/common/alterguardian_contained/collect",
            "dontstarve/HUD/research_unlock",
            "dontstarve/HUD/research_available",



            "summerevent/carnival_games/feedchicks/station/endbell",
            "summerevent/carnival_games/herding_station/endbell",
            "summerevent/carnival_games/memory/spawn_rewards_endbell",
            "dontstarve/creatures/together/deer/bell_idle",
            "dontstarve/creatures/together/deer/bell",
            "hookline/common/trophyscale_fish/bell",
            "dontstarve_DLC001/common/firesupressor_warningbell",
            "dontstarve_DLC001/common/glommer_bell",
            "yotb_2021/common/cow_bell",
}